import json
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

try:
    BostonHousingPricingApp_DBFS = DBFSConnector.fetch(
        [], {}, "5e99b1cb98f009ca79eb1270", spark, "{'url': '/Demo/BostonTrain.csv', 'file_type': 'Delimeted', 'delimiter': ',', 'is_header': 'Use Header Line'}")

    BostonHousingPricingApp_AutoFE = TransformationMain.run(["5e99b1cb98f009ca79eb1270"], {"5e99b1cb98f009ca79eb1270": BostonHousingPricingApp_DBFS}, "5e99b1cb98f009ca79eb1271", spark, json.dumps({"FE": [{"transformationsData": {}, "feature": "CRIM", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "51", "mean": "4.52", "stddev": "13.45", "min": "0.01301", "max": "88.9762", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "ZN", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "51", "mean": "8.86", "stddev": "18.55", "min": "0.0", "max": "100.0", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "INDUS", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "51", "mean": "10.47", "stddev": "6.03", "min": "1.32", "max": "19.58", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "CHAS", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "51", "mean": "0.04", "stddev": "0.2", "min": "0.0", "max": "1.0", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "NOX", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "51", "mean": "0.55", "stddev": "0.12", "min": "0.405", "max": "0.871", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "RM", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "51", "mean": "6.36", "stddev": "0.77", "min": "4.926", "max": "8.725", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "AGE", "type": "real", "selected": "True", "replaceby": "mean", "stats": {
                                                            "count": "51", "mean": "69.83", "stddev": "26.4", "min": "6.5", "max": "100.0", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "DIS", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "51", "mean": "3.94", "stddev": "2.16", "min": "1.4165", "max": "8.9067", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "RAD", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "51", "mean": "8.98", "stddev": "8.11", "min": "1.0", "max": "24.0", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "TAX", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "51", "mean": "397.92", "stddev": "152.65", "min": "193.0", "max": "666.0", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "PTRATIO", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "51", "mean": "18.09", "stddev": "2.06", "min": "14.7", "max": "21.0", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "B", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "51", "mean": "351.22", "stddev": "102.24", "min": "0.32", "max": "396.9", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "LSTAT", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "51", "mean": "12.4", "stddev": "6.99", "min": "2.98", "max": "31.99", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "MEDV", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "51", "mean": "21.9", "stddev": "9.79", "min": "7.4", "max": "50.0", "missing": "0"}, "transformation": ""}]}))

    functionRegression(BostonHousingPricingApp_AutoFE, [
                       "CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM", "AGE", "DIS", "RAD", "TAX", "PTRATIO", "B", "LSTAT"], "MEDV")

except Exception as ex:
    print(ex)
